In [1]:
import numpy as np
table = np.array([[50,40,20],[30,25,15]])
table

array([[50, 40, 20],
       [30, 25, 15]])

In [2]:
print(table.sum(axis=0))
print(table.sum(axis=1))
print(table.sum())

[80 65 35]
[110  70]
180


In [3]:
n = table.sum()
col = table.sum(axis=0)/n
row = table.sum(axis=1)/n
print(col)
print(row)

[ 0.44444444  0.36111111  0.19444444]
[ 0.61111111  0.38888889]


In [4]:
for index, x in np.ndenumerate(table):
    print(index, x)

(0, 0) 50
(0, 1) 40
(0, 2) 20
(1, 0) 30
(1, 1) 25
(1, 2) 15


In [5]:
expected = np.empty(table.shape)
for index, x in np.ndenumerate(table):
    pA = row[index[0]]
    pB = col[index[1]]
    expected[index] = pA*pB*n
print(expected)

[[ 48.88888889  39.72222222  21.38888889]
 [ 31.11111111  25.27777778  13.61111111]]


In [6]:
(((table-expected)**2)/expected).sum()

0.30184101612673114

In [7]:
from scipy.stats import chi2
chi = chi2.isf(q=0.05, df=2)
print(chi)

5.99146454711
